export const copy = {
  nav: { explore: "Les parcours", lessons: "Les cours", games: "Les jeux", about: "Pourquoi SigMath ?", contribute: "Participer" },
  skip: "Aller directement aux niveaux",
  eyebrow: "Les mathématiques sont déjà là",
  heroTitleA: "Une ville.",
  heroTitleB: "Mille idées.",
  heroBody: "Les maths se comprennent en essayant. Découvre des cours clairs, manipule des images et relève de petits défis à ton rythme.",
  begin: "Jouer pour comprendre",
  levels: "Voir tous les niveaux",
  scroll: "Défiler pour entrer dans la ville",
  chapter: "Chapitre",
  hotspots: "points à découvrir",
  tierIntro: "À chaque classe, son parcours",
  tierTitle: "On commence où ?",
  tierBody: "Trois parcours du primaire au collège. Choisis ta classe, ou reprends une notion pour retrouver confiance. La 6e fait partie du cycle 3.",
  visit: "Explorer ce niveau",
  lessonEyebrow: "Leçon à la une · 12 min",
  lessonTitle: "Les fractions sont déjà à table.",
  lessonBody: "Une pizza, quatre personnes : tu sais déjà partager ! Découvre comment écrire ces parts avec des fractions, puis compare-les en images.",
  lessonCta: "Ouvrir la leçon",
  missionEyebrow: "Comprendre avant de mémoriser",
  missionTitle: "Tu as le droit de ne pas encore savoir.",
  missionBody: "Une formule devient plus simple quand tu vois ce qu’elle raconte. SigMath accompagne les élèves du CP à la 3e avec des cours en français, des exemples du quotidien et des expériences à refaire autant que nécessaire. Parents et enseignants peuvent aussi s’en servir pour expliquer autrement.",
  footerTagline: "Les maths, un déclic à la fois. Du CP à la 3e, en français.",
  openSource: "Projet open source",
  menu: "Ouvrir le menu",
  theme: "Changer de thème",
  language: "Changer de langue",
};
