export const labNotes = {
  garden: ["10 unités forment une dizaine.", "10 ones make one ten."],
  place: ["Un chiffre vaut dix fois plus dans la colonne à sa gauche.", "A digit is worth ten times more in the column to its left."],
  largePlace: ["Regroupe les chiffres par trois pour lire milliers et millions.", "Group digits in threes to read thousands and millions."],
  line: ["Plus un nombre est à droite, plus il est grand.", "The further right a number is, the greater it is."],
  signedLine: ["Une distance est positive ou nulle ; une variation peut être négative.", "Distance is zero or positive; a change can be negative."],
  calculation: ["Ajouter réunit ; soustraire retire ; multiplier répète un groupe.", "Addition joins; subtraction removes; multiplication repeats a group."],
  multiplication: ["a × b, c’est a rangées de b objets.", "a × b means a rows of b objects."],
  story: ["Représente chaque étape avant de choisir le calcul.", "Represent each step before choosing the calculation."],
  sharing: ["Total = nombre de groupes × part de chacun + reste.", "Total = number of groups × each share + remainder."],
  pizza: ["Le dénominateur compte toutes les parts égales ; le numérateur, celles choisies.", "The denominator counts all equal pieces; the numerator counts the selected ones."],
  length: ["La longueur se lit entre le zéro de la règle et l’extrémité.", "Read the length from the ruler’s zero to the end of the object."],
  measure: ["1 L = 1 000 mL ; 1 kg = 1 000 g. La quantité reste la même.", "1 L = 1,000 mL; 1 kg = 1,000 g. The quantity stays the same."],
  money: ["100 centimes valent 1 €. La monnaie rendue est la différence.", "100 cents make €1. Change is the difference."],
  clock: ["60 minutes font 1 heure, pas 100.", "60 minutes make 1 hour, not 100."],
  shape: ["Reconnais une figure par ses propriétés, même quand elle tourne.", "Identify a shape by its properties, even when it turns."],
  solid: ["Un pavé contient longueur × largeur × hauteur cubes unités.", "A cuboid contains length × width × height unit cubes."],
  symmetry: ["Deux points symétriques sont à la même distance de l’axe.", "Reflected points are the same distance from the mirror line."],
  data: ["Compare les hauteurs avec une même échelle.", "Compare bar heights using the same scale."],
  fraction: ["Une fraction est un nombre : elle peut dépasser 1.", "A fraction is a number: it can be greater than 1."],
  decimal: ["100 centièmes forment une unité entière.", "100 hundredths make one whole."],
  balance: ["L’égalité est vraie quand les deux membres ont la même valeur.", "An equality is true when both sides have the same value."],
  area: ["L’aire compte la surface en unités carrées ; le périmètre mesure le contour.", "Area counts square units inside; perimeter measures the boundary."],
  angle: ["Un angle droit vaut 90° ; un angle plat vaut 180°.", "A right angle is 90°; a straight angle is 180°."],
  probability: ["Sur un dé équilibré, chaque face a une chance sur six à chaque lancer.", "On a fair die, each face has a one-in-six chance on every roll."],
  proportion: ["Multiplier le nombre de personnes multiplie chaque ingrédient de la même façon.", "Scaling the number of people scales every ingredient by the same factor."],
  robot: ["L’ordre des instructions et l’orientation changent le trajet.", "Instruction order and orientation change the route."],
  triangle: ["Les trois angles d’un triangle ont une somme de 180°.", "The three angles of a triangle add up to 180°."],
  function: ["Dans f(x) = ax + b, a règle la pente et b la valeur pour x = 0.", "In f(x) = ax + b, a sets the slope and b the value at x = 0."],
  vector: ["Additionne les coordonnées pour additionner deux déplacements.", "Add coordinates to add two displacements."],
} as const;

export type LabId = keyof typeof labNotes;

export const lessonLabs: Record<string, LabId> = {
  "kids/counting-collections": "garden",
  "kids/place-value": "place",
  "kids/order-number-line": "line",
  "kids/add-subtract": "calculation",
  "kids/mental-calculation": "calculation",
  "kids/multiply-divide": "sharing",
  "kids/word-problems": "story",
  "kids/fractions-parts": "pizza",
  "kids/lengths": "length",
  "kids/mass-capacity": "measure",
  "kids/money": "money",
  "kids/time-duration": "clock",
  "kids/plane-shapes": "shape",
  "kids/solids": "solid",
  "kids/space-symmetry": "symmetry",
  "kids/data-charts": "data",
  "cycle-3/large-whole-numbers": "largePlace",
  "cycle-3/fractions-measure-quotient": "fraction",
  "cycle-3/decimal-numbers": "decimal",
  "cycle-3/mental-written-calculation": "multiplication",
  "cycle-3/early-algebra": "balance",
  "cycle-3/multi-step-problems": "story",
  "cycle-3/proportionality": "proportion",
  "cycle-3/lengths-perimeters": "area",
  "cycle-3/areas": "area",
  "cycle-3/angles": "angle",
  "cycle-3/mass-capacity": "measure",
  "cycle-3/time-duration": "clock",
  "cycle-3/plane-geometry": "shape",
  "cycle-3/solids-volumes": "solid",
  "cycle-3/space-movements": "robot",
  "cycle-3/data-investigations": "data",
  "cycle-3/probability": "probability",
  "cycle-3/computational-thinking": "robot",
  "middle-school/fractions": "pizza",
  "middle-school/negative-numbers": "signedLine",
  "middle-school/equations": "balance",
  "middle-school/triangles": "triangle",
  "middle-school/probability": "probability",
};

// Lab components now render first, outside the optional reading. Keep MDX prose,
// equations and exercises intact, and avoid rendering the same lab twice.
export function readingWithoutLabs(source: string) {
  return source.replace(/^\s*<(?:[A-Za-z]+Lab|NumberGarden|FractionSlicer)\s*\/>(?:\r?\n)?/gm, "\n").trim();
}
