export const labNotes = {
  garden: "10 unités forment une dizaine.",
  place: "Un chiffre vaut dix fois plus dans la colonne à sa gauche.",
  largePlace: "Regroupe les chiffres par trois pour lire milliers et millions.",
  line: "Plus un nombre est à droite, plus il est grand.",
  signedLine: "Une distance est positive ou nulle ; une variation peut être négative.",
  calculation: "Ajouter réunit ; soustraire retire ; multiplier répète un groupe.",
  multiplication: "a × b, c’est a rangées de b objets.",
  story: "Représente chaque étape avant de choisir le calcul.",
  sharing: "Total = nombre de groupes × part de chacun + reste.",
  pizza: "Le dénominateur compte toutes les parts égales ; le numérateur, celles choisies.",
  length: "La longueur se lit entre le zéro de la règle et l’extrémité.",
  measure: "1 L = 1 000 mL ; 1 kg = 1 000 g. La quantité reste la même.",
  money: "100 centimes valent 1 €. La monnaie rendue est la différence.",
  clock: "60 minutes font 1 heure, pas 100.",
  shape: "Reconnais une figure par ses propriétés, même quand elle tourne.",
  solid: "Un pavé contient longueur × largeur × hauteur cubes unités.",
  symmetry: "Deux points symétriques sont à la même distance de l’axe.",
  data: "Compare les hauteurs avec une même échelle.",
  fraction: "Une fraction est un nombre : elle peut dépasser 1.",
  decimal: "100 centièmes forment une unité entière.",
  balance: "L’égalité est vraie quand les deux membres ont la même valeur.",
  area: "L’aire compte la surface en unités carrées ; le périmètre mesure le contour.",
  angle: "Un angle droit vaut 90° ; un angle plat vaut 180°.",
  probability: "Sur un dé équilibré, chaque face a une chance sur six à chaque lancer.",
  proportion: "Multiplier le nombre de personnes multiplie chaque ingrédient de la même façon.",
  robot: "L’ordre des instructions et l’orientation changent le trajet.",
  triangle: "Les trois angles d’un triangle ont une somme de 180°.",
} as const;

export type LabId = keyof typeof labNotes;

export const lessonLabs: Record<string, LabId> = {
  "kids/counting-collections": "garden",
  "kids/place-value": "place",
  "kids/order-number-line": "line",
  "kids/add-subtract": "calculation",
  "kids/mental-calculation": "calculation",
  "kids/multiply-divide": "sharing",
  "kids/word-problems": "story",
  "kids/fractions-parts": "pizza",
  "kids/lengths": "length",
  "kids/mass-capacity": "measure",
  "kids/money": "money",
  "kids/time-duration": "clock",
  "kids/plane-shapes": "shape",
  "kids/solids": "solid",
  "kids/space-symmetry": "symmetry",
  "kids/data-charts": "data",
  "cycle-3/large-whole-numbers": "largePlace",
  "cycle-3/fractions-measure-quotient": "fraction",
  "cycle-3/decimal-numbers": "decimal",
  "cycle-3/mental-written-calculation": "multiplication",
  "cycle-3/early-algebra": "balance",
  "cycle-3/multi-step-problems": "story",
  "cycle-3/proportionality": "proportion",
  "cycle-3/lengths-perimeters": "area",
  "cycle-3/areas": "area",
  "cycle-3/angles": "angle",
  "cycle-3/mass-capacity": "measure",
  "cycle-3/time-duration": "clock",
  "cycle-3/plane-geometry": "shape",
  "cycle-3/solids-volumes": "solid",
  "cycle-3/space-movements": "robot",
  "cycle-3/data-investigations": "data",
  "cycle-3/probability": "probability",
  "cycle-3/computational-thinking": "robot",
  "middle-school/fractions": "pizza",
  "middle-school/negative-numbers": "signedLine",
  "middle-school/equations": "balance",
  "middle-school/triangles": "triangle",
  "middle-school/probability": "probability",
};

// Lab components now render first, outside the optional reading. Keep MDX prose,
// equations and exercises intact, and avoid rendering the same lab twice.
export function readingWithoutLabs(source: string) {
  return source.replace(/^\s*<(?:[A-Za-z]+Lab|NumberGarden|FractionSlicer)\s*\/>(?:\r?\n)?/gm, "\n").trim();
}
